import Plus from "lucide-react/dist/esm/icons/plus.mjs";
import X from "lucide-react/dist/esm/icons/x.mjs";
import { useState, type FormEvent } from "react";
import type { AssetIncident, IncidentStatus } from "../../domain/asset-incidents";
import type { UserRole } from "../../domain/auth";
import { formatDateTime } from "../../shared/format";
import { useAssetRecords } from "../assets/use-assets";
import { useCreateIncident, useIncidents, useReviewIncident } from "./use-incidents";

const statusLabel: Record<IncidentStatus, string> = { pending: "Aguardando análise", internal_repair: "Reparo interno", external_assistance: "Assistência externa", warranty: "Garantia", resolved: "Resolvida", disposed: "Baixa" };

export function IncidentsPage({ role }: { role: UserRole }) {
  const [creating, setCreating] = useState(false); const [reviewing, setReviewing] = useState<AssetIncident | null>(null); const incidents = useIncidents(); const canReview = role !== "operator";
  return <div><header className="page-heading"><div><p className="path-label">C:\ ATIVOS &gt; OCORRÊNCIAS</p><h1>Problemas e manutenção</h1><p>Rastreie defeitos pelo patrimônio, série, responsável e lote de aquisição.</p></div><button className="button button--primary" onClick={() => setCreating(true)}><Plus /> Relatar problema</button></header><section className="panel inventory-panel"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Ativo</th><th>Responsável anterior</th><th>Problema</th><th>Lote</th><th>Situação</th><th>Registro</th>{canReview ? <th>Ação</th> : null}</tr></thead><tbody>{incidents.data?.map((item) => <tr key={item.id}><td className="mono">{item.id.slice(0, 8)}</td><td>{item.productName}<small className="table-subline">{item.assetTag}{item.serialNumber ? ` · Série ${item.serialNumber}` : ""}</small></td><td>{item.custodianName ?? "Não informado"}</td><td>{item.description}</td><td className="mono">{item.receiptBatchId?.slice(0, 8) ?? "Anterior ao controle"}</td><td>{statusLabel[item.status]}</td><td>{formatDateTime(item.reportedAt)}<small className="table-subline">{item.reporter}</small></td>{canReview ? <td><button disabled={item.status === "resolved" || item.status === "disposed"} className="button button--secondary button--compact" onClick={() => setReviewing(item)}>Analisar</button></td> : null}</tr>)}</tbody></table></div>{!incidents.isPending && incidents.data?.length === 0 ? <div className="page-state">Nenhuma ocorrência registrada.</div> : null}</section><CreateIncidentDialog open={creating} onClose={() => setCreating(false)} />{reviewing ? <ReviewIncidentDialog key={reviewing.id} incident={reviewing} onClose={() => setReviewing(null)} /> : null}</div>;
}

function CreateIncidentDialog({ open, onClose }: { open: boolean; onClose(): void }) {
  const assets = useAssetRecords({ search: "", locationId: null, status: null }); const create = useCreateIncident(); const [assetId, setAssetId] = useState(""); const [custodianName, setCustodian] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState(""); if (!open) return null;
  async function submit(event: FormEvent) { event.preventDefault(); try { setError(""); await create.mutateAsync({ assetId, custodianName: custodianName.trim() || null, description }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header><div><p className="path-label">OCORRÊNCIA</p><h2>Relatar problema em ativo</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><div className="form-grid form-grid--single"><label><span>Ativo patrimonial</span><select required value={assetId} onChange={(event) => setAssetId(event.target.value)}><option value="">Selecione por patrimônio ou série</option>{assets.data?.filter((asset) => asset.status !== "disposed" && asset.status !== "maintenance").map((asset) => <option key={asset.id} value={asset.id}>{asset.assetTag}{asset.serialNumber ? ` · ${asset.serialNumber}` : ""} — {asset.productName}</option>)}</select></label><label><span>Colaborador que devolveu o equipamento</span><input maxLength={120} value={custodianName} onChange={(event) => setCustodian(event.target.value)} placeholder="Ex.: Maria" /></label><label><span>Descrição do problema</span><textarea required minLength={10} maxLength={1000} rows={4} value={description} onChange={(event) => setDescription(event.target.value)} /></label></div><p className="form-hint">Ao registrar, o ativo ficará indisponível e o gestor receberá a ocorrência para análise.</p>{error ? <p className="form-error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={create.isPending}>Registrar ocorrência</button></footer></form></section></div>;
}

function ReviewIncidentDialog({ incident, onClose }: { incident: AssetIncident | null; onClose(): void }) { const review = useReviewIncident(); const [status, setStatus] = useState<IncidentStatus>("internal_repair"); const [resolutionNote, setNote] = useState(""); const [error, setError] = useState(""); if (!incident) return null; async function submit(event: FormEvent) { event.preventDefault(); try { setError(""); await review.mutateAsync({ id: incident!.id, version: incident!.version, status, resolutionNote }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } } return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header><div><p className="path-label">ANÁLISE {incident.id.slice(0, 8)}</p><h2>{incident.assetTag} · {incident.productName}</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><p>{incident.description}</p><div className="form-grid form-grid--single"><label><span>Decisão</span><select value={status} onChange={(event) => setStatus(event.target.value as IncidentStatus)}><option value="internal_repair">Reparo interno</option><option value="external_assistance">Assistência externa</option><option value="warranty">Acionar garantia</option><option value="resolved">Reparado e disponível</option><option value="disposed">Baixa patrimonial</option></select></label><label><span>Parecer do gestor</span><textarea required minLength={10} maxLength={1000} rows={4} value={resolutionNote} onChange={(event) => setNote(event.target.value)} /></label></div>{error ? <p className="form-error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={review.isPending}>Registrar decisão</button></footer></form></section></div>; }
