import Plus from "lucide-react/dist/esm/icons/plus.mjs";
import X from "lucide-react/dist/esm/icons/x.mjs";
import { useState, type FormEvent } from "react";
import type { UserRole } from "../../domain/auth";
import type { ReplenishmentPriority, ReplenishmentRequest } from "../../domain/replenishment";
import { formatDateTime } from "../../shared/format";
import { useInventory, useLocations } from "../inventory/use-inventory";
import { useCreateReplenishmentRequest, useReplenishmentRequests, useReviewReplenishmentRequest } from "./use-replenishment";
import { CreateMovementDialog } from "../movements/create-movement-dialog";

export function ReplenishmentPage({ role }: { role: UserRole }) {
  const [creating, setCreating] = useState(false);
  const [reviewing, setReviewing] = useState<ReplenishmentRequest | null>(null);
  const [receiving, setReceiving] = useState<ReplenishmentRequest | null>(null);
  const requests = useReplenishmentRequests();
  const canReview = role !== "operator";
  return <div><header className="page-heading"><div><p className="path-label">C:\ SOLICITAÇÕES &gt; REPOSIÇÃO</p><h1>Reposição de produtos</h1><p>{canReview ? "Decida entre transferência interna, compra externa ou atendimento parcial." : "Solicite produtos existentes no catálogo para abastecer sua unidade."}</p></div><button className="button button--primary" onClick={() => setCreating(true)}><Plus /> Nova solicitação</button></header><section className="panel inventory-panel"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Data</th><th>Destino</th><th>Solicitante</th><th>Prioridade</th><th>Produtos</th><th>Situação</th>{canReview ? <th>Ação</th> : null}</tr></thead><tbody>{requests.data?.map((request) => <tr key={request.id}><td className="mono">{request.id.slice(0, 8)}</td><td>{formatDateTime(request.requestedAt)}</td><td>{request.destinationLocation}</td><td>{request.requester}</td><td>{priorityLabel(request.priority)}</td><td>{request.items.map((item) => `${item.productName} (${item.requestedQuantity})`).join(", ")}<small className="table-subline">{request.items.some((item) => item.purchaseQuantity > 0) ? `Compra recebida: ${request.items.reduce((total, item) => total + item.receivedQuantity, 0)} de ${request.items.reduce((total, item) => total + item.purchaseQuantity, 0)} · ` : ""}{request.justification}</small></td><td><span className={`request-status request-status--${request.status}`}>{statusLabel(request.status)}</span></td>{canReview ? <td>{request.status === "pending" ? <button className="button button--compact button--secondary" onClick={() => setReviewing(request)}>Analisar</button> : ["approved", "partially_approved", "in_fulfillment"].includes(request.status) && request.items.some((item) => item.receivedQuantity < item.purchaseQuantity) ? <button className="button button--compact button--secondary" onClick={() => setReceiving(request)}>Registrar recebimento</button> : request.reviewer ?? "Concluída"}</td> : null}</tr>)}</tbody></table></div>{requests.isPending ? <div className="page-state">Carregando solicitações…</div> : null}{requests.isError ? <div className="page-state page-state--error">Não foi possível carregar as solicitações.</div> : null}{!requests.isPending && requests.data?.length === 0 ? <div className="page-state">Nenhuma reposição solicitada.</div> : null}</section><CreateDialog open={creating} onClose={() => setCreating(false)} /><ReviewDialog request={reviewing} onClose={() => setReviewing(null)} />{receiving ? <CreateMovementDialog key={receiving.id} open role={role} replenishmentRequest={receiving} onClose={() => setReceiving(null)} /> : null}</div>;
}

function CreateDialog({ open, onClose }: { open: boolean; onClose(): void }) {
  const locations = useLocations(); const inventory = useInventory(""); const create = useCreateReplenishmentRequest();
  const [destinationLocationId, setDestination] = useState(""); const [priority, setPriority] = useState<ReplenishmentPriority>("normal"); const [justification, setJustification] = useState(""); const [items, setItems] = useState([{ productId: "", quantity: 1 }]); const [error, setError] = useState("");
  if (!open) return null;
  async function submit(event: FormEvent) { event.preventDefault(); try { setError(""); await create.mutateAsync({ destinationLocationId, priority, justification, items }); onClose(); setJustification(""); setItems([{ productId: "", quantity: 1 }]); } catch (reason) { setError(errorText(reason)); } }
  return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header><div><p className="path-label">ABASTECIMENTO</p><h2>Solicitar reposição</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><div className="form-grid"><label>Unidade de destino<select required value={destinationLocationId} onChange={(event) => setDestination(event.target.value)}><option value="">Selecione</option>{locations.data?.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Prioridade<select value={priority} onChange={(event) => setPriority(event.target.value as ReplenishmentPriority)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><div className="form-grid form-grid--single">{items.map((item, index) => <div className="form-grid" key={index}><label>Produto<select required value={item.productId} onChange={(event) => setItems((current) => current.map((entry, position) => position === index ? { ...entry, productId: event.target.value } : entry))}><option value="">Selecione</option>{inventory.data?.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select></label><label>Quantidade<input required type="number" min={1} max={1000000} value={item.quantity} onChange={(event) => setItems((current) => current.map((entry, position) => position === index ? { ...entry, quantity: Number(event.target.value) } : entry))} /></label>{items.length > 1 ? <button className="button button--secondary button--compact" type="button" onClick={() => setItems((current) => current.filter((_, position) => position !== index))}>Remover</button> : null}</div>)}<button className="button button--secondary button--compact" type="button" onClick={() => setItems((current) => [...current, { productId: "", quantity: 1 }])}>Adicionar produto</button><label>Justificativa<textarea required minLength={10} maxLength={1000} value={justification} onChange={(event) => setJustification(event.target.value)} /></label></div>{error ? <p className="form-error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={create.isPending}>Registrar solicitação</button></footer></form></section></div>;
}

function ReviewDialog({ request, onClose }: { request: ReplenishmentRequest | null; onClose(): void }) {
  if (!request) return null;
  return <ReviewDialogContent key={request.id} request={request} onClose={onClose} />;
}
function ReviewDialogContent({ request, onClose }: { request: ReplenishmentRequest; onClose(): void }) {
  const locations = useLocations(); const review = useReviewReplenishmentRequest(); const [note, setNote] = useState(""); const [error, setError] = useState("");
  const [decisions, setDecisions] = useState(() => request.items.map((item) => ({ itemId: item.id, transferQuantity: 0, purchaseQuantity: 0, sourceLocationId: null as string | null, purchaseReference: null as string | null })));
  async function submit(event: FormEvent) { event.preventDefault(); try { setError(""); await review.mutateAsync({ id: request.id, version: request.version, note, items: decisions }); onClose(); } catch (reason) { setError(errorText(reason)); } }
  function patch(index: number, value: Partial<(typeof decisions)[number]>) { setDecisions((current) => current.map((entry, position) => position === index ? { ...entry, ...value } : entry)); }
  return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><header><div><p className="path-label">ANÁLISE {request.id.slice(0, 8)}</p><h2>Decidir atendimento</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><p>{request.justification}</p><div className="form-grid form-grid--single">{request.items.map((item, index) => <fieldset key={item.id}><legend>{item.productName} · solicitado {item.requestedQuantity} · saldo no pedido {item.stockSnapshot}</legend><div className="form-grid"><label>Transferir<input type="number" min={0} max={item.requestedQuantity} disabled={item.trackingType === "serialized"} value={decisions[index]!.transferQuantity} onChange={(event) => patch(index, { transferQuantity: Number(event.target.value) })} /></label><label>Comprar<input type="number" min={0} max={item.requestedQuantity} value={decisions[index]!.purchaseQuantity} onChange={(event) => patch(index, { purchaseQuantity: Number(event.target.value) })} /></label><label>Origem<select disabled={decisions[index]!.transferQuantity === 0} value={decisions[index]!.sourceLocationId ?? ""} onChange={(event) => patch(index, { sourceLocationId: event.target.value || null })}><option value="">Selecione</option>{locations.data?.filter((location) => location.id !== request.destinationLocationId).map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Referência de compra<input maxLength={120} value={decisions[index]!.purchaseReference ?? ""} onChange={(event) => patch(index, { purchaseReference: event.target.value || null })} /></label></div>{item.trackingType === "serialized" ? <small>Transferências patrimoniais serão liberadas quando houver seleção individual dos ativos.</small> : null}</fieldset>)}<label>Parecer do gestor<textarea required minLength={10} maxLength={1000} value={note} onChange={(event) => setNote(event.target.value)} /></label></div>{error ? <p className="form-error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={review.isPending}>Registrar decisão</button></footer></form></section></div>;
}

function priorityLabel(priority: ReplenishmentPriority) { return ({ low: "Baixa", normal: "Normal", high: "Alta", urgent: "Urgente" } as const)[priority]; }
function statusLabel(status: ReplenishmentRequest["status"]) { return ({ pending: "Pendente", approved: "Aprovada", partially_approved: "Parcial", rejected: "Recusada", in_fulfillment: "Em atendimento", fulfilled: "Concluída", cancelled: "Cancelada" } as const)[status]; }
function errorText(reason: unknown) { return reason instanceof Error ? reason.message : String(reason); }
